# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish
    - name: Deploy with SCP
      uses: i3h/deploy-with-scp@v1
      with:
        src: /home/runner/work/testapp/testapp/bin/Release/net8.0/publish
        dest: /var/www/TestApp
        username: root
        server-ip: mav3n.tech
        ssh-key: ${{ secrets.MAV3N_TECH_SSH }}
   
