# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish
    - name: Deploy with SCP
      uses: nogsantos/scp-deploy@master
      with:
        src: /home/runner/work/testapp/testapp/TestApp/bin/Release/net8.0/publish/*
        host: mavenweb.mav3n.tech
        remote: /var/www/TestApp
        port: 22
        user: root
        key: ${{ secrets.MAV3N_TECH_SSH }}
    - name: Restart App
      uses: fifsky/ssh-action@v0.0.6
      with:
    # Command to execute on the remote server.
        command: systemctl restart testapp.service
    # Hostname or IP address of the server.
        host: mavenweb.mav3n.tech
    # String that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
        key: ${{ secrets.MAV3N_SSH_KEY}}
          
   
