# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        eval `ssh-agent -s`
        echo ${{secrets.MAV3N_TECH_SSH}} > ~/.ssh/mav3n.tech
        chmod 0600 ~/.ssh/mav3n.tech
        ssh-add ~/.ssh/mav3n.tech
    - name: Deploy
      run: scp -r -i ~/.ssh/mav3n.tech /home/runner/work/testapp/testapp/bin/Release/net8.0/publish root@mavenweb.mav3n.tech:/var/www/TestApp 
